### ISSUE TITLE
features文件夹内没有数据

### ISSUE THREAD

**Issue by Hianghua** [weimingboya/DFT#1]
你好， 非常感谢您的论文， 对我的帮助特别大， 我想跟着您提供的代码转一下模型，学习

可是features 文件夹内还没有数据， 

有时间的时候可以上传数据吗？ 

谢谢~

**Comment by weimingboya** [comment]
你好，感谢你关注我们的工作～
由于特征文件太大，我们已经在tools文件夹下提供了相应的特征抽取代码
请使用它们自行抽取，如果还有问题可以进一步与我们联系

**Comment by xwz8910** [comment]
你好，我在提取VinVL特征的时候看到需要在这个链接（https://github.com/pzzhang/VinVL/blob/main/DOWNLOAD.md ）里面下载预训练好的特征，但是这个链接里的下载页面已经失效打不开了。请问您能不能分享一下下面三个数据吗？十分感谢！
[COCO 2014 Train/Val Image Features (~50G)](https://biglmdiag.blob.core.windows.net/vinvl/image_features/coco_X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/model_0060000/)

[COCO 2014 Test Image Features (~16G)](https://biglmdiag.blob.core.windows.net/vinvl/image_features/coco_X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/model_0060000/coco2014test/)

[COCO 2015 Test Image Features (~32G)](https://biglmdiag.blob.core.windows.net/vinvl/image_features/coco_X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/model_0060000/coco2015test/)

**Comment by weimingboya** [comment]
path/to/azcopy copy <folder-link> <target-address> --resursive"
官网里用这个命令下载，试过了吗？
