### ISSUE TITLE
训练精度一直没达到您预训练的精度

### ISSUE THREAD

**Issue by songchuanle-1** [weimingboya/DFT#15]
大佬，我设置都一样的，用A100跑Cider只能训练到126.7 4090跑只能达到127.3，是还有什么参数不一致吗？想请问下您使用什么显卡跑的
    parser = argparse.ArgumentParser(description='Dual Transformer')
    parser.add_argument('--output', type=str, default='DualModel')
    parser.add_argument('--exp_name', type=str, default='DFT')
    parser.add_argument('--device', type=str, default='cuda:0')
    parser.add_argument('--batch_size', type=int, default=20)
    parser.add_argument('--workers', type=int, default=8)

    parser.add_argument('--N_enc', type=int, default=3)
    parser.add_argument('--N_dec', type=int, default=3)

    parser.add_argument('--xe_base_lr', type=float, default=1e-4)
    parser.add_argument('--rl_base_lr', type=float, default=5e-6)
    parser.add_argument('--use_rl', action='store_true')
    parser.add_argument('--resume_last', action='store_true')
    parser.add_argument('--resume_best', action='store_true')
    parser.add_argument('--clip_path', type=str, default='../COCO2014_RN50x4_copy.hdf5')
    parser.add_argument('--vinvl_path', type=str, default='../COCO2014_VinVL.hdf5')

    parser.add_argument('--image_folder', type=str, default='/media/user/FILE_DATA/song/coco2014')
    parser.add_argument('--annotation_folder', type=str, default='annotations')
    args = parser.parse_args()

**Comment by weimingboya** [comment]
我用的2080TI，127.3好像也没差多少，可以算复现成功啦

**Comment by songchuanle-1** [comment]
好的谢谢啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月19日(周五) 中午11:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [weimingboya/DFT] 训练精度一直没达到您预训练的精度 (Issue #15)




 
我用的2080TI，127.3好像也没差多少，可以算复现成功啦

**Comment by sty514** [comment]
May I ask where you downloaded your clip grid features?
