### ISSUE TITLE
下载特征出错

### ISSUE THREAD

**Issue by songchuanle-1** [weimingboya/DFT#2]
$ azcopy copy 'https://biglmdiag.blob.core.windows.net/vinvl/image_features/coco_X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/model_0060000/' 'feature'  --recursive
INFO: Scanning...
INFO: Autologin not specified.

failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public

**Comment by weimingboya** [comment]
It could be that the download link they provided is not working. I'll see if I can upload it to the cloud, but it may take a while due to the large feature file.

**Comment by weimingboya** [comment]
哈喽，VinVL特征请查收～
链接: https://pan.baidu.com/s/1Ypy0299KWHTLsD8AD1D0jA 提取码: xxrt 复制这段内容后打开百度网盘手机App，操作更方便哦
