### ISSUE TITLE
azcopy无法下载

### ISSUE THREAD

**Issue by jackIrving** [weimingboya/DFT#3]
你好大佬，使用Vinvl官方的azcopy命令下载时出现这个问题：
failed to perform copy command due to error: failed to discern source credential type: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public。
大佬可以在空余时间上传一下吗
COCO 2014 Train/Val Image Features (~50G)

COCO 2014 Test Image Features (~16G)
十分感谢！！！

**Comment by weimingboya** [comment]
你好 感谢关注我们的工作 我这几天尽快上传一下！

**Comment by jackIrving** [comment]
十分感谢大佬的回复，期待大佬的上传！！！

**Comment by weimingboya** [comment]
哈喽，VinVL特征请查收～
链接: https://pan.baidu.com/s/1Ypy0299KWHTLsD8AD1D0jA 提取码: xxrt 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by jackIrving** [comment]
十分感谢大佬的上传，太感动了！！！祝大佬学业和事业蒸蒸日上！！！
