### ISSUE TITLE
请问可以提供COCO2014_RN50x4_GLOBAL.hdf5和论文预训练的checkpoint吗？

### ISSUE THREAD

**Issue by moon4869** [weimingboya/DFT#6]
VinVL数据集有在其他issue里看到新的链接，但是COCO2014_RN50x4_GLOBAL.hdf5和预训练模型checkpoint还未找到，[该链接里相关文件已失效](https://pan.baidu.com/s/17ik-2OZGFaQ5-AzCCWkL9w)，想问下能否再补充下相关数据，辛苦大佬，同时非常感谢大佬的优秀工作！

**Comment by weimingboya** [comment]
COCO2014_RN50x4_GLOBAL.hdf5有抽取代码，详见tools中extract_clip_feature.py
模型权重：https://pan.baidu.com/s/17ik-2OZGFaQ5-AzCCWkL9w#list/path=%2F (密码：ska0)
